### ISSUE TITLE
ignore __pycache__ folder is not working good

### ISSUE THREAD

**Issue by EmadDeve20** [xcodz-dot/denver-api#28]
so I think your ```.gitignore``` file is not good!
because your use it is not true: ``` __pycache__```
if you using just like ``` __pycache__/```  its work it.

but I think, it better you using ```.gitignore``` file for python:
https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by xcodz-dot** [comment]
Yes, I will surely change that. Also I just have started to learn the best practices for Python and GitHub so I have to clean up this codebase soon enough

**Comment by EmadDeve20** [comment]
good luck (brother/sister) :D
